runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest

- name: pycrypto
  version: latest